### ISSUE TITLE
Error "template with C linkage"

### ISSUE THREAD

**Issue by Bardo91** [TommyX12/darknet-cpp-wrapper#3]
Hi I was trying to compile the project using CMake and I am getting several errors related with `template with C linkage` in several cuda functions similar to this one:

```
In file included from /usr/local/cuda-8.0/include/cuda_runtime.h:90:0,
                 from /home/bardo91/programing/3rdparty/darknet-cpp-wrapper/src/darknet.h:14,
                 from /home/bardo91/programing/3rdparty/darknet-cpp-wrapper/src/utils.h:5,
                 from /home/bardo91/programing/3rdparty/darknet-cpp-wrapper/src/darknet_detector.h:4,
                 from /home/bardo91/programing/3rdparty/darknet-cpp-wrapper/src/darknet.hpp:5,
                 from /home/bardo91/programing/3rdparty/darknet-cpp-wrapper/src/main.cpp:1:
/usr/local/cuda-8.0/include/channel_descriptor.h:107:1: error: template with C linkage
 template<class T> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc(void)
 ^
/usr/local/cuda-8.0/include/channel_descriptor.h:140:1: error: template specialization with C linkage
 template<> __inline__ __host__ cudaChannelFormatDesc cudaCreateChannelDesc<char>(void)
 ^
```

I was able to compile and use Darknet project using their make file and I have been using but now I want to use it in a project using cpp and I got blocked at this point. Do you have any guess of what can I do for solving it? 

This is the make file I am using.

[CMakeLists.txt](https://github.com/TommyX12/darknet-cpp-wrapper/files/1239893/CMakeLists.txt)

Thanks a lot.

**Comment by rickythink** [comment]
same error...

**Comment by mrlzla** [comment]
Have you already fixed the error?

**Comment by Bardo91** [comment]
I uploaded a cpp library wrapper in this repo: https://github.com/Bardo91/darknet_cpp

And this is an example of CMakeLists.txt for using it in a project 
[CMakeLists.txt](https://github.com/TommyX12/darknet-cpp-wrapper/files/1458238/CMakeLists.txt)

I hope it helps
